### ISSUE TITLE
UI DESIGN: Design the UI screens for this app

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-frontend#1]
You are to design the UI screens in a very simple and intuitive flow for this application.
Details to be discussed with the project maintainer.

Expected skillset: UI Designer

ETA: 3 days.

**Comment by Kingsuite** [comment]
I'd like to handle this task. It's my first time contributing to this project

**Comment by abdegenius** [comment]
Can I tackle this one?

**Comment by od-hunter** [comment]
May I be assigned to this? This are links to previous designs I've done: https://github.com/mubarak23/chainevents-frontend/issues/6

https://github.com/Peerprotocol/peer-on-strk/issues/8

https://github.com/sivicstudio/starkludo/issues/30

kindly assign me please, I'm up for the task

**Comment by starknetbrother** [comment]
May I take care of this?

**Comment by Storyofmujahid** [comment]
This would be a good opportunity to give my best in solving this issue. Check my attention to detail here https://dribbble.com/Mujaaahiid

**Comment by emarc99** [comment]
I have both UI/UX and frontend development experience. I can do it.

**Comment by Storyofmujahid** [comment]
Based on my experience and skillset, I will be able to give my best and tackle this task.

**Comment by Joe-joe25** [comment]
I'll really love to work on this, Below is the link to my portfolio
https://www.behance.net/josephyanum
https://dribbble.com/Joseph_terkuma

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by KVMillz** [comment]
Hi, I'm a creative designer brand and UI designer can I handle this task? attached is th link to my portforlio
www.behance.net/kwelbevictor

**Comment by ShantelPeters** [comment]
May I pick this up?
