### ISSUE TITLE
Build the FAQs component

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-frontend#2]
https://www.figma.com/design/brLKsEY4NW58tmT9iFqziX/Transverse?node-id=62-45&t=y6LFPiGZq5CNqG6n-4

here is the link to the figma design, replicate this design by creating a file in the components folder and writing your code in there then you import this component into the FAQs page so that i can access this component when i navigate to /faqs.

For any icons you might need, use lucide-react icons.

**Comment by sonkiee** [comment]
May I try my hand at this?

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through Design, Study, and be in sync with the flow of the Design
- I will then start the FAQ implementation inside the `app/faqs/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, lucide-react icons e.t.c
- I will make sure the implementation works across all devices

## ETA
12 Hours

**Comment by emarc99** [comment]
Mind if I take this issue?

**Comment by akintola4** [comment]
I confirmed the design in the figma file and i'm sure i can do it within the estimated time given to me and I have good track record of building frontend website i have them on my twitter and various repos in my github this is an example (https://ooido-kc4l.vercel.app/)

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience and I have worked with frontend technologies like React, NextJS, Javascript/Typescript. I'm a recent graduate of the Web3bridge Africa the foremost and premier blockchain developer community. I have made contributions in many open source projects and i look forward to contributing to this. My approach to this will be to

1- Review the project structure, figma link and necessary files 
2- Implement the faqs component with the proper color scheme  and functionalties.

ET: 1 day

**Comment by ussyalfaks** [comment]
I'd like to work on replicating this design. I’ll create a file in the components folder and write the code there. After that, I’ll import the component into the FAQs page so it can be accessed when navigating to /faqs . For any icons i will use lucide-react icons.
