### ISSUE TITLE
Build the Footer component

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-frontend#3]
https://www.figma.com/design/brLKsEY4NW58tmT9iFqziX/Transverse?node-id=62-46&t=y6LFPiGZq5CNqG6n-4

here is the link to the figma design, replicate this design by creating a file in the components folder and writing your code in there then you import this component into the footer page so that i can access this component when i navigate to /footer.

For any icons you might need, use lucide-react icons.

**Comment by sonkiee** [comment]
I’d love to work on this task.

**Comment by ekumamatthew** [comment]
Could I take over this issue?

**Comment by Levi-Ojukwu** [comment]
Hello Dprof-in-tech, I will like to work on this issue.

## About Me 
I am a web3 full-stack developer with expertise in blockchain technology and frontend engineering. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How to tackle the issue
- To tackle this issue, I will start by creating a component file inside the component folder
- Then I will style and develope the footer component
- Then I will import the file to the App file to enable the footer component to be added to the application.

If given this issue, I will ensure full compliance with the team and the team's guidline.

## ETA - 8 - 10 hours max

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through Design, Study, and be in sync with the flow of the Design
- I will then start the Footer implementation inside the `app/footer/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, lucide-react icons e.t.c
- I will make sure the implementation works across all devices

## ETA
12 Hours

**Comment by akintola4** [comment]
May I try my hand at this?I have also gone through the figma design to know what I'm working with it and i know i can deliver within the estimated time

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience and I have worked with frontend technologies like React, NextJS, Javascript/Typescript. I'm a recent graduate of the Web3bridge Africa the foremost and premier blockchain developer community. I have made contributions in many open source projects and i look forward to contributing to this. My approach to this will be to

1- Review the project structure, figma link and necessary files 
2- Implement the footer component with the proper color scheme  and functionalties.

ET: 1 day

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe I can handle this, and I would to contribute to the project. Can take on this task?

**Comment by ussyalfaks** [comment]
I'd like to work on replicating this design. I’ll create a file in the components folder and write the code there. After that, I’ll import the component into the footer page so it can be accessed when navigating to /footer. For any icons i will use lucide-react icons.

**Comment by Dprof-in-tech** [comment]
good day @sonkeydotcom , whats the progress on this issue?
