### ISSUE TITLE
Build the Testimonials component

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-frontend#4]
https://www.figma.com/design/brLKsEY4NW58tmT9iFqziX/Transverse?node-id=62-44&t=y6LFPiGZq5CNqG6n-4

here is the link to the figma design, replicate this design by creating a file in the components folder and writing your code in there then you import this component into the testimonials page so that i can access this component when i navigate to /testimonial.

For any icons you might need, use lucide-react icons.

**Comment by sonkiee** [comment]
Is this issue still available?

**Comment by ekumamatthew** [comment]
Could I take a shot at this?

**Comment by Levi-Ojukwu** [comment]
Hello Dprof-in-tech, I will like to work on this issue.

## About Me 
I am a web3 full-stack developer with expertise in blockchain technology and frontend engineering. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How to tackle the issue
- To tackle this issue, I will start by creating a file inside the component folder.
- Then I will develop and build the UI of the page.
- I will then proceed by getting the testimonial of the users from the database and displays it on the developed testimonial page.
- I will make the page dynamic and responsive to all devices.


If assigned this issue, I will ensure full compliance with the team and the team's guidelines.

## ETA - 12 hours

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through Design, Study, and be in sync with the flow of the Design
- I will then start the Testimonials implementation inside the `app/testimonials/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, lucide-react icons e.t.c
- I will make sure the implementation works across all devices

## ETA
12 Hours

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience and I have worked with frontend technologies like React, NextJS, Javascript/Typescript. I'm a recent graduate of the Web3bridge Africa the foremost and premier blockchain developer community. I have made contributions in many open source projects and i look forward to contributing to this. My approach to this will be to

1- Review the project structure, figma link and necessary files 
2- Implement the testimonials component with the proper color scheme  and functionalties.

ET: 1 day

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design and I would love to contribute to this project. Can take on this task?

**Comment by Dprof-in-tech** [comment]
good day @FrankiePower , whats the progress on this issue?

**Comment by FrankiePower** [comment]
i haven't been able to get access to the figma file. i need a password

**Comment by Dprof-in-tech** [comment]
> i haven't been able to get access to the figma file. i need a password

send me a dm on telegram to get the figma password
