### ISSUE TITLE
Build the Header component

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-frontend#6]
https://www.figma.com/design/brLKsEY4NW58tmT9iFqziX/Transverse?node-id=66-47&t=y6LFPiGZq5CNqG6n-4

here is the link to the figma design, replicate this design by creating a file in the components folder and writing your code in there then you import this component into the header page so that i can access this component when i navigate to /header

For any icons you might need, use lucide-react icons.

**Comment by emarc99** [comment]
Mind if I try this one? 
Latest FE developed is here https://github.com/emarc99/no-fail

**Comment by sonkiee** [comment]
Could I take on this issue?

**Comment by ekumamatthew** [comment]
May I take this issue on?

**Comment by Pvsaint** [comment]
Can I take this from here?
If it's still available,  I'm a front-end and smart contract developer,  proficient in reactjs, nextjs, solidify and cairo

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through Design, Study, and be in sync with the flow of the Design
- I will then start the Header implementation inside the `app/header/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, lucide-react icons e.t.c
- I will make sure the implementation works across all devices

## ETA
10 Hours

**Comment by davedumto** [comment]
Hi,
My name is David, and I am a frontend developer skilled in JavaScript, TypeScript, React.js, Next.js, and Tailwind CSS. I will replicate the provided Figma design by creating a new component file in the components folder, ensuring all required icons are implemented using lucide-react.

I’ll import this component into the header page and ensure it is accessible at /header. ETA: 2 days.

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience and I have worked with frontend technologies like React, NextJS, Javascript/Typescript. I'm a recent graduate of the Web3bridge Africa the foremost and premier blockchain developer community. I have made contributions in many open source projects and i look forward to contributing to this. My approach to this will be to

1- Review the project structure, figma link and necessary files 
2- Implement the header component with the proper color scheme  and functionalties.

ET: 1 day

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe I can handle this, and I would to contribute to the project. Can take on this task?

**Comment by ussyalfaks** [comment]
I'd like to work on replicating this design. I’ll create a file in the components folder and write the code there. After that, I’ll import the component into the header page so it can be accessed when navigating to /header.

**Comment by Dprof-in-tech** [comment]
Good day @ussyalfaks , whats the progress on this issue

**Comment by 0xdevcollins** [comment]
Can I work on this?

**Comment by ussyalfaks** [comment]
> Good day @ussyalfaks , whats the progress on this issue
I noticed that the issue was initially assigned to me
😞😞

**Comment by Dprof-in-tech** [comment]
It was but there was no reply from you so it got reassigned

**Comment by yusuftomilola** [comment]
Can i still apply for this if it's available?

**Comment by Dprof-in-tech** [comment]
good day @0xdevcollins , please what is the progress on this issue?

**Comment by GoSTEAN** [comment]
Can I work on this?

**Comment by 0xdevcollins** [comment]
I will make a pr in the next 3hrs. I am having power issues
